=== wanderingivan/newssite-example/src/test/resources/test.dtd
<!ELEMENT dataset (
    users*,
    articles*,
    paragraphs*,
    comments*,
    groups+,
    group_authorities+,
	group_members+,
	chats+,
	messages+,
	chats_join_table+,
    tasks*
)>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id CDATA #IMPLIED
    username CDATA #REQUIRED
    email CDATA #REQUIRED
    password CDATA #REQUIRED
    enabled CDATA #REQUIRED
    details CDATA #IMPLIED
    imagePath CDATA #IMPLIED
>

<!ELEMENT articles EMPTY>
<!ATTLIST articles
    article_id CDATA #IMPLIED
    headline CDATA #REQUIRED
    author_id CDATA #REQUIRED
    category CDATA #REQUIRED
    caption CDATA #REQUIRED
    imagePath CDATA #IMPLIED
    lastEdited CDATA #IMPLIED
    hits CDATA #IMPLIED
>

<!ELEMENT paragraphs EMPTY>
<!ATTLIST paragraphs
	paragraph_id CDATA #IMPLIED
	text CDATA #REQUIRED
	article_id CDATA #REQUIRED
	article_order CDATA #REQUIRED
>

<!ELEMENT comments EMPTY>
<!ATTLIST comments 
	comment_id CDATA #IMPLIED
	message CDATA #REQUIRED
	posted CDATA #IMPLIED
	poster_id CDATA #REQUIRED
	article_id CDATA #REQUIRED
>

<!ELEMENT groups EMPTY>
<!ATTLIST groups 
	id CDATA #IMPLIED
	group_name CDATA #REQUIRED
>

<!ELEMENT group_members EMPTY>
<!ATTLIST group_members 
	id CDATA #IMPLIED
	username CDATA #REQUIRED
	group_id CDATA #REQUIRED
>

<!ELEMENT group_authorities EMPTY>
<!ATTLIST group_authorities 
	group_id CDATA #REQUIRED
	authority CDATA #REQUIRED
>

<!ELEMENT chats EMPTY>
<!ATTLIST chats
	chat_id CDATA #IMPLIED
	lastUpdate CDATA #IMPLIED 
>

<!ELEMENT messages EMPTY>
<!ATTLIST messages 
	message_id CDATA #IMPLIED
	message CDATA #REQUIRED
	posted CDATA #IMPLIED
	poster_id CDATA #REQUIRED
	chat_id CDATA #REQUIRED
>

<!ELEMENT chats_join_table EMPTY>
<!ATTLIST chats_join_table
	user_id CDATA #REQUIRED 
	chat_id CDATA #REQUIRED
>

<!ELEMENT tasks EMPTY>
<!ATTLIST tasks
	task_id CDATA #IMPLIED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	assigner CDATA #REQUIRED
	assignee CDATA #REQUIRED
>

=== wanderingivan/newssite-example/src/test/resources/DbTestDataSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset PUBLIC "//UNKNOWN/" "test.dtd">
<dataset>
	<users user_id="1" username="username1" email="some@email" password="Bar" enabled="1" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350ProfilePic.png" details="Placeholder Description"/>
	<users user_id="2" username="username2" email="some@email1" password="Bar" enabled="1" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350ProfilePic.png" details="Placeholder Description"/>
	<users user_id="3" username="username3" email="some@email2" password="Bar" enabled="0" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350ProfilePic.png" details="Placeholder Description"/>
	<users user_id="4" username="username4" email="some@email3" password="Bar" enabled="1" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350ProfilePic.png" details="Placeholder Description"/>
	<users username="username5" email="some@email4"  password="Bar" enabled="1" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350ProfilePic.png" details="Placeholder Description"/>

	<articles article_id="3" headline="headline1" caption="sometext" category="politics" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="2" lastEdited="2015-09-08" hits="1"/>
	<articles article_id="4" headline="headline2" caption="sometext" category="politics" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="2" lastEdited="2015-09-01" hits="100"/>
	<articles headline="headline23" caption="sometext" category="sports" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="2" lastEdited="2015-09-05" hits="120"/>
	<articles headline="headline234" caption="sometext" category="sports" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="2" lastEdited="2015-09-05" hits="120"/>
	<articles headline="headline3" caption="sometext" category="entertainment" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="2" lastEdited="2015-09-04" hits="0"/>
	<articles headline="headline6" caption="sometext" category="entertainment" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="2" lastEdited="2015-09-04" hits="0"/>
	<articles article_id="5" headline="headline4" caption="sometext" category="international" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="3" lastEdited="2015-09-02" hits="0"/>
	<articles article_id="7" headline="headline7" caption="sometext" category="international" imagePath="/home/shadow1207/Examples/Bootstrap/NewsSite/img/350x350News.png" author_id="3" lastEdited="2015-09-02" hits="0"/>
	
	<paragraphs article_id="3" text="paragraph text" article_order="0"/>
	<paragraphs article_id="4" article_order="0" text="paragraph text"/>
	<paragraphs article_id="4" article_order="1" text="paragraph text"/>
	<paragraphs article_id="4" article_order="2" text="paragraph text"/>
	
	<comments article_id="3" message="message" poster_id="1" posted="2015-09-08"/>
	<comments article_id="3" message="message" poster_id="1" posted="2015-09-04" comment_id="2"/>
	<comments article_id="3" comment_id="1000" message="messageToEdit" poster_id="3" posted="2015-09-03"/>
	<comments article_id="4" comment_id="3" message="messageToDelete" poster_id="1" posted="2015-09-02"/>

	
	<groups group_name="users" id="1"/>
	<groups group_name="writers" id="2"/>	
	<groups group_name="admins" id="3"/>
	
	<group_authorities group_id="1" authority="ROLE_USER"/>
	<group_authorities group_id="2" authority="ROLE_WRITER"/>
	<group_authorities group_id="3" authority="ROLE_ADMIN"/>

	<group_members group_id="2" username="username2"/>
	<group_members group_id="2" username="username3"/>
	<group_members group_id="3" username="username5"/>
	<group_members group_id="1" username="username1"/>
	<group_members group_id="1" username="username4"/>
	
	<chats chat_id="1" lastUpdate="2015-09-03"/>
	<chats chat_id="2" lastUpdate="2015-09-03"/>
	<messages message_id="3" message="message" chat_id="1" poster_id="1" posted="2015-09-02 00:00:01"/>
	<messages message="message3" chat_id="1" poster_id="2" posted="2015-09-03 00:00:02"/>
	<messages message="message2" chat_id="2" poster_id="2" posted="2015-09-04"/>
	<chats_join_table user_id="1" chat_id="1"/>
	<chats_join_table user_id="2" chat_id="1"/>
	<chats_join_table user_id="3" chat_id="2"/>
	<chats_join_table user_id="2" chat_id="2"/>

    <tasks task_id="1" assigner="username2" name="testTask1" description="test description" assignee="username1"/>
    <tasks assigner="username2" name="testTask2" description="test description" assignee="username3"/>
</dataset>
